apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-demo-gerard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gerardtarrats/test2.git'
    path: argo
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rollout-demo-gerard
  syncPolicy:
    automated: {}
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
