apiVersion: v1
kind: Service
metadata:
  name: canary
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30581
  selector:
    app: canary-demo
  type: NodePort
